### ISSUE TITLE
Issue on page /images_3d.html

### ISSUE THREAD

**Issue by issa-garcia** [nipraxis/textbook#37]
Hello,

The last cell of images_3d.Rmd is not working properly on jupyter notebook. The problem is that you cannot cycle through slices by clicking and dragging the cursor over the images of each of the planes.

![image](https://user-images.githubusercontent.com/68673381/180746302-8002b8af-a702-4387-b895-09d446d62607.png)

I suspect it might have something to do with matplotlib's backends, but after a lot of time troubleshooting, I have not been able to fix it. Please let me know what information would be useful to you (versions of everything in the jupyter notebook, etc.). I am happy to provide the information that you think would help.

Regards

**Comment by effigies** [comment]
This is dynamic in an interactive shell session, but I don't know that it can be done in a notebook.
