### ISSUE TITLE
Issue on page /what_is_an_image.html

### ISSUE THREAD

**Issue by sofiezomerman** [nipraxis/textbook#38]
I imported nipraxis and executed the next step:

structural_fname = nipraxis.fetch_file('ds114_sub009_highres.nii')

When executing this line I keep getting the following error: "AttributeError: module 'nipraxis' has no attribute 'fetch_file'

**Comment by matthew-brett** [comment]
Thanks for the report.  How are you running the notebook - on your own machine, or on our cloud setup?

**Comment by sofiezomerman** [comment]
Hi! I am running the notebook using visual studio code on my own machine

**Comment by matthew-brett** [comment]
How did you install the `nipraxis` module?  What version do you have?

```
$ pip show nipraxis
```

**Comment by sofiezomerman** [comment]
I have version 0.3.6 and used "import nipraxis" in my Python file in visual studio code

**Comment by matthew-brett** [comment]
How strange.  I have version 0.3.6, and I do have `fetch_file`:

```
[ins] In [1]: import nipraxis

[ins] In [2]: nipraxis.fetch_file?
Signature: nipraxis.fetch_file(rel_url)
Docstring:
Fetch data file from local cache, or registry
    
File:      ~/Library/Python/3.10/lib/python/site-packages/nipraxis/_fetcher.py
Type:      function

```

What do you get for `nipraxis.__file__`?  Is it possible you have stray `nipraxis` folder that gets on the path before the module?

**Comment by sofiezomerman** [comment]
When running nipraxis.fetch.file? I get the following: 
>>> nipraxis.fetch_file?
  File "<stdin>", line 1
    nipraxis.fetch_file?
                       ^
SyntaxError: invalid syntax

When trying help(nipraxis.fetch.file):
>>> help(nipraxis.fetch_file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'nipraxis' has no attribute 'fetch_file'
>>> 

When running: nipraxis.__file__
>>> nipraxis.__file__
'/data/szomerman/nipraxis-work/nipraxis.py'
>>>

**Comment by matthew-brett** [comment]
Right - the last line tells me that you have a file `nipraxis.py` that got imported as the `nipraxis` module, instead of the `nipraxis` module you installed with `pip`.  Try renaming that file, and restarting the kernel - does that help?

**Comment by sofiezomerman** [comment]
How do I restart the kernel using visual studio code? As I am not working in Jupyter notebook

**Comment by sofiezomerman** [comment]
I removed the file and now I get the following error: ModuelNotFoundError: No module named 'nipraxis'

**Comment by matthew-brett** [comment]
Aha - yes - this is a typical problem in visual studio code - that it's hard to work out which Python you are using, and what state that Python interpreter is in.   What has happened here is that the Python that you are using is not the same as the one that `pip` is installing into - so you need to track down in VSCode, which Python it is using, and either change the Python to be the one you're installing into, or install `nipraxis` and the other modules into the Python VSCode is using.

**Comment by sofiezomerman** [comment]
Thank you so much! There was a mismatch between the Python version VSC was using and the one that nipraxis was installed on; it is fixed now.

**Comment by ZviBaratz** [comment]
Just a note for future reference – try using the [`%pip`](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pip) [built-in magic command](https://ipython.readthedocs.io/en/stable/interactive/magics.html#built-in-magic-commands) to run the `pip` executable associated with the notebook's kernel. I find it to be a convenient way to make sure I avoid these mismatch problems.

**Comment by matthew-brett** [comment]
@sofiezomerman - would you mind closing the issue if it is resolved?
