### ISSUE TITLE
Add some detail to /assert.html

### ISSUE THREAD

**Issue by effigies** [nipraxis/textbook#40]
Although the page includes testing in the title, it is probably worth emphasizing in the text that asserts are for development, testing, and debugging, and should not be used as a mechanism to intentionally raise errors at runtime.

They will be optimized out with `-O` flags. Their primary use case is to state an explicit assumption prior to a block of code that uses it, which can be safely removed during production while verifying the condition in development and testing.

* https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement
* https://docs.python.org/3/using/cmdline.html#cmdoption-O

**Comment by matthew-brett** [comment]
All true - but - any chance of a PR?
